### ISSUE TITLE
Upstream example-analyzer to rustdoc proper

### ISSUE THREAD

**Issue by jyn514** [willcrichton/example-analyzer#2]
Trying to write the blockers down before I forget them again. The main issue is Rustdoc needs some way to emit its *own* metadata, and needs to be run on examples before running on the main library. The sequence looks like

```sh
rustc --profile check src/lib.rs
example-analyzer examples/a/main.rs --extern my_crate=/path/to/libmy_crate.rlib --output call-locations.json
rustdoc src/lib.rs --call-locations /path/to/call-locations.json
```

The end-goal is for example-analyzer to be part of rustdoc, and for cargo to take care of invoking it in the proper order. That would look something like
```sh
rustc --profile check src/lib.rs
rustdoc --only-show-call-locations examples/a/main.rs --extern my_crate=/path/to/libmy_crate.rlib --output call-locations.json
rustdoc src/lib.rs --call-locations /path/to/call-locations.json
```
It would be nice to go even further and generate examples whenever rustdoc runs on a crate (that would allow e.g. showing examples for hyper when documenting warp). That would need rustdoc to generate proper metadata that's stored with the other metadata of the crate (in the `.rlib`). I have no idea how hard this would be, but I'm guessing the answer is 'hard'. The invocation for that would look something like
```sh
rustdoc hyper/src/lib.rs
rustdoc warp/src/lib.rs --extern my_crate=/path/to/libmy_crate.rlib 
```

So there are two changes to make (assuming example-analyzer is already part of rustdoc), which I think could happen independently:
1. Change rustdoc to emit its own metadata when compiling a crate. I guess that would need someway to update the existing metadata in place? I need to check whether rustdoc actually needs `rustc --profile check` to run before it does.
2. Change cargo to document examples before documenting the main crate.

See also
- Cargo thread about the examples: https://rust-lang.zulipchat.com/#narrow/stream/246057-t-cargo/topic/Documentation.20outputs.
- Compiler thread about whether rustdoc can update metadata in-place: https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp/topic/Is.20metadata.20updated.20in.20place.3F

**Comment by jyn514** [comment]
> I need to check whether rustdoc actually needs rustc --profile check to run before it does.

Yes for dependencies, because rustdoc doesn't support `--emit=metadata`, so it doesn't have a way to generate .rlibs. No for the crate actually being documented.

**Comment by jyn514** [comment]
Also this will probably need an RFC at some point given the number of changes :/ but I can walk you through that process.

**Comment by jyn514** [comment]
> Compiler thread about whether rustdoc can update metadata in-place: https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp/topic/Is.20metadata.20updated.20in.20place.3F

Metadata doesn't help because there's no dependency from warp -> hyper, only from hyper -> warp. So the compiler doesn't know to load the metadata (if it did, example-analyzer could just use `-Zalways-encode-mir` and this would all be much easier). I think an alternate solution could be for cargo to document crates in *reverse* order: Say you have `log -> hyper -> warp` - you document warp *first*, finding uses of the hyper API, store them in the out-of-band output file, then document `hyper`, then document `log` in the same way. Then changing this to examples is a natural extension: just document the examples before documenting `hyper`. And no changes to metadata loading are necessary, rustdoc just needs a place to store `call-locations.json` (which it already has, the `doc/` folder).

**Comment by willcrichton** [comment]
I think it's ok for now to punt on getting examples from external crates. In the future, I'm imagining a separate crater-like tool that would scrape examples from all the users of a crate. It could even do something fancy like cluster common usage patterns like in [this paper](https://dl.acm.org/doi/abs/10.1145/3173574.3174154). 

If we just focus on examples within a crate, does that involve many significant changes to rustdoc? As you said, we just need a place to store call-locations.json. It's ok if the process requires two invocations of rustdoc, since this is a workflow that we'll primarily use on docs.rs.

**Comment by jyn514** [comment]
> If we just focus on examples within a crate, does that involve many significant changes to rustdoc? As you said, we just need a place to store call-locations.json. It's ok if the process requires two invocations of rustdoc, since this is a workflow that we'll primarily use on docs.rs.

Well, adding example-analyzer to rustdoc at all is a giant change, but I don't think it needs changes to metadata. It just needs cargo to start running rustdoc on examples before documenting the library.

**Comment by jyn514** [comment]
> Well, adding example-analyzer to rustdoc at all is a giant change

In particular, I expect it to completely break https://doc.rust-lang.org/nightly/rustdoc/advanced-features.html#cfgdoc-documenting-platform-specific-or-feature-specific-information.

**Comment by jyn514** [comment]
This is now implemented on nightly 🎉
